### ISSUE TITLE
An error occurred while running the client: Gateway(DisallowedGatewayIntents)

### ISSUE THREAD

**Issue by chaodziejg** [TudbuT/projbotv3#1]
An error occurred while running the client: Gateway(DisallowedGatewayIntents) how to fix this

**Comment by TudbuT** [comment]
This problem is not in my code, but instead with the discord bot setup. Check these: 
![image](https://user-images.githubusercontent.com/48156391/200561995-d0b376b1-bebb-480f-86bd-f9d2082fa0a7.png)
