### ISSUE TITLE
An error occurred while running the client: "401: Unauthorized"

### ISSUE THREAD

**Issue by gamecube-github** [TudbuT/projbotv3#2]
Full error message:
An error occurred while running the client: Http(UnsuccessfulRequest(ErrorResponse { status_code: 401, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v10/users/@me", query: None, fragment: None }, error: DiscordJsonError { code: 0, message: "401: Unauthorized", errors: [] } }))

**Comment by gamecube-github** [comment]
got it working

**Comment by TudbuT** [comment]
For others having this issue in the future finding this: This is usually because the token is invalid or something else that causes the API to not accept the authorization.
